version: "3.9"

services:

  postgres:
    image: "postgres:14.4"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "pg_isready", "--quiet", "--dbname=postgres", "--username=postgres" ]
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=carl
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres12345
    networks:
      opendutnet:

networks:
  opendutnet:
    name: opendut_network
    external: true  # Use a pre-existing network

volumes:
  postgres_data:
